language: node_js
sudo: false
before_install:
  - npm install -g npm
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.3"

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  skip_cleanup: true
  email: "schreiber.arthur@googlemail.com"
  api_key:
    secure: pSwLyKvYC3sxv0qxvbZy2W4ENXeE7/7emnnFJ8BMEYBTel/g+An0fN9lbtZSPoOaCEUVWEa2DzCHvU0jZ+qiOB1iZ+Swav9Ka0aOW54mtiig7oQY3GZpNvMkBhMPmkyIloECjFKNpxnZyi/ZHUjJLhu04o36xcAWASowfs3Mdwg=
  on:
    tags: true
    repo: pekim/tedious
    node: "0.10"
