language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.3"

deploy:
  provider: npm
  email: "schreiber.arthur@googlemail.com"
  api_key:
    secure: qqKBWeZEc5jvGuM8j44sgPNxqkrLaveRt1SIRqFZG9JRcA0i/t/vxRxhGSelnDymjzfQ4M71jAHQe9DJ14rjzMeFdA7qPUXfHjgmhQ4EQW3zBhVzAA2JxBZeoA2R6dcGkY6jsStjPQPBpTsUkFprDG96pHndB3mK4DJ+a6cs8ew=
  on:
    tags: true
    repo: pekim/tedious
    node: "0.10"
